apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-tracker-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/shared_storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-tracker-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
