apiVersion: v1
kind: Service
metadata:
  name: task-tracker-service
spec:
  type: NodePort
  selector:
    app: task-tracker
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30007
